export const metadata = {
    title: "Admin",
    description: "Generated by create next app",
  };
  
  const AdminLayout = ({children}) => {
    return (
      <div>
        {children}
      </div>
    )
  }
   
  export default AdminLayout;