// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
'use client';

import { useUser } from "@/context/UserContext";

import NavBar from "@/components/Client/Dashboard/navbar";
import Footer from "@/components/Client/Dashboard/Footer";

// export const metadata = {
//   title: "Profile",
//   description: "Generated by create next app",
// };

export default function ProfileLayout({ children }) {

  const { user, login, logout } = useUser();
  
  return (    
      <div>
        <NavBar user={user} />
          <main>{children}</main>
        <Footer />
      </div>
  );
}
