'use client';

import { useUser } from "@/context/UserContext";

import NavBar from "@/components/Client/Dashboard/navbar";
import Footer from "@/components/Client/Dashboard/Footer";

// export const metadata = {
//   title: "Profile",
//   description: "Generated by create next app",
// };

export default function ProfileLayout({ children }) {

  const { user, login, logout } = useUser();
  // console.log(sessionStorage.getItem('accessToken'), ' is token');
  return (
    <div>
      <NavBar user={user} logout={logout} />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
